name: sharding-repl-cache

services:
  configSrv: #сервер конфигурации
    image: mongo:latest #docker образ
    container_name: configSrv 
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.101
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",  #запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s


  shard1-1: #1-й шард 
    image: mongo:latest
    container_name: shard1-1
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.111
    volumes:
      - shard1-1-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet", #указание названия replica set
        "rs1", #название replica set
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-1-a: #1-й шард реплика а
    image: mongo:latest
    container_name: shard1-1-a
    restart: always
    ports:
      - "27031:27031"
    networks:
      app-network:
        ipv4_address: 173.17.0.112
    volumes:
      - shard1-1-a-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet", #указание названия replica set
        "rs1", #название replica set
        "--bind_ip_all",
        "--port",
        "27031"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-1-b: #1-й шард реплика b
    image: mongo:latest
    container_name: shard1-1-b
    restart: always
    ports:
      - "27032:27032"
    networks:
      app-network:
        ipv4_address: 173.17.0.113
    volumes:
      - shard1-1-b-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet", #указание названия replica set
        "rs1", #название replica set
        "--bind_ip_all",
        "--port",
        "27032"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-2: #2-й шард 
    image: mongo:latest
    container_name: shard1-2
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.121
    volumes:
      - shard1-2-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet", #указание названия replica set
        "rs2", #название replica set
        "--bind_ip_all", 
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-2-a: #2-й шард реплика а
    image: mongo:latest
    container_name: shard1-2-a
    restart: always
    ports:
      - "27041:27041"
    networks:
      app-network:
        ipv4_address: 173.17.0.122
    volumes:
      - shard1-2-a-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet", #указание названия replica set
        "rs2", #название replica set
        "--bind_ip_all", 
        "--port",
        "27041"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-2-b: #2-й шард реплика b
    image: mongo:latest
    container_name: shard1-2-b
    restart: always
    ports:
      - "27042:27042"
    networks:
      app-network:
        ipv4_address: 173.17.0.123
    volumes:
      - shard1-2-b-data:/data/db
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet", #указание названия replica set
        "rs2", #название replica set
        "--bind_ip_all", 
        "--port",
        "27042"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s


  mongos_router: #роутер
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.102
    command:
      [
        "mongos", #обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27017", #передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s


  redis_1:
    image: "redis:latest"
    container_name: redis_1
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.201

  redis_2:
    image: "redis:latest"
    container_name: redis_2
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.202

  redis_3:
    image: "redis:latest"
    container_name: redis_3
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.203

  redis_4:
    image: "redis:latest"
    container_name: redis_4
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_4_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.204

  redis_5:
    image: "redis:latest"
    container_name: redis_5
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_5_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.205

  redis_6:
    image: "redis:latest"
    container_name: redis_6
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_6_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.206


  pymongo_api:
    image: kazhem/pymongo_api:1.0.0
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - configSrv
      - mongos_router
      - redis_1
    networks:
      app-network:
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis_2"


networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data:
  shard1-1-data:
  shard1-1-a-data:
  shard1-1-b-data:  
  shard1-2-data:
  shard1-2-a-data:
  shard1-2-b-data:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
